### ISSUE TITLE
Script not updating anymore

### ISSUE THREAD

**Issue by terabyte-gc** [loadletter/mangaupdates-urlfix#11]
I noticed that the script doesn't auto update anymore in Firefox and after taking a quick look I see that the current 1.7.20 version still says version 1.7.0 in the tags and thus FF doesn't pick up that there is an update.

**Comment by loadletter** [comment]
It is updated

1.7 is the version of the script
.20 is the revision of the group data

Since this issue already came up, what should I do to make this clear?
Replace "Release 1.7.20" with "Revision 20"?

**Comment by terabyte-gc** [comment]
Sorry, I guess I haven't explained myself properly.

The issue is this line in the JS file:
// @version     1.7.0

Since, as you said, this is revision 20 of the group data if the version line gets changed to:
// @version     1.7.20

Firefox will properly detect that there is a new version out and update the script, otherwise it keeps 'seeing' the same version and never updates. For now I simply re-import it once in a while manually (mainly when I notice a missing group link). If the issue is that you want to keep it still version 1.7.0 maybe you could use something like 1.7.0.20 to indicate the revision and let FF/Scriptish auto-update the script.

**Comment by loadletter** [comment]
The script doesn't need updating because it always fetches the latest data from github.
If a link is missing it probably hasn't been added yet or github is down and there is no cached data (very unlikely).

The first version of the script relied on greasemonkey/tampermonkey autoupdating, but it proved to be unreliable so I rewrote the script not to be changed unless needed.
