### ISSUE TITLE
[Feature Request] Group URL navigate directly to the Site

### ISSUE THREAD

**Issue by MammothJerk** [loadletter/mangaupdates-urlfix#12]
i very rarely go onto a groups page for anything other then to find their website.

is it possible to have an option that all group links such as "https://www.mangaupdates.com/groups.html?id=5217" will automatically redirect to the Site? thus saving a click and a few seconds

i have 625 manga in my reading list so it adds up quickly

**Comment by loadletter** [comment]
Something like this?
https://github.com/loadletter/mangaupdates-urlfix/raw/redirect/mangaupdates_urlfix.user.js

It adds a link to toggle redirection at the bottom of the [scanlator list page](https://www.mangaupdates.com/groups.html)

**Comment by MammothJerk** [comment]
Yes that works almost perfect, a little nitpicky thing is that it still flashes the mangaupdates group page for a few milliseconds.
i just added these lines to my mangaupdates theme
```
    @-moz-document url-prefix(https://www.mangaupdates.com/groups.html?id=) {
body {
   display: none !important;
 }
}
```
its a bit of a long "loading page" now but other then that perfect :D

If i can be so bold as to ask for a bit more.
in https://www.mangaupdates.com/mylist.html all the titles will have a number next to their title to indicate an unread chapter. clicking that number bring you to this page "https://www.mangaupdates.com/releases.html?search=103618&stype=series" could this page also redirect to the latest release group page and subsequently to their Site? 
the group at the top of the group column or the group with the most recent date, whatever makes the most sense

**Comment by loadletter** [comment]
>And if I can be so bold as to ask for a bit more.
in https://www.mangaupdates.com/mylist.html all the titles will have a number next to their title to indicate an unread chapter. clicking that number bring you to this page "https://www.mangaupdates.com/releases.html?search=103618&stype=series" could this page also redirect to the latest release group page and subsequently to their Site? 

[Done](https://github.com/loadletter/mangaupdates-urlfix/raw/redirect/mangaupdates_urlfix.user.js)
It adds a toggle link next to the export button

The flashing page can't be resolved since the script has to wait for the network, hiding it will cause an entry without a website to remain hidden.

**Comment by MammothJerk** [comment]
Thank you very much :D
